-- Insert sample jobs for different career fields
INSERT INTO jobs (title, company, location, job_type, salary_range, description, requirements, skills_required, experience_level, career_field) VALUES
('Software Engineer', 'TechCorp', 'San Francisco, CA', 'full-time', '$120,000 - $180,000', 'Build scalable web applications using modern technologies.', ARRAY['Bachelor''s in CS or related field', '3+ years experience', 'Strong problem-solving skills'], ARRAY['JavaScript', 'React', 'Node.js', 'SQL'], 'mid', 'technology'),
('Data Science Intern', 'DataLabs', 'Remote', 'internship', '$25 - $35/hour', 'Work on machine learning projects and data analysis.', ARRAY['Currently pursuing degree in CS/Statistics', 'Python experience', 'Understanding of ML concepts'], ARRAY['Python', 'Machine Learning', 'Data Analysis', 'SQL'], 'entry', 'technology'),
('Marketing Manager', 'BrandCo', 'New York, NY', 'full-time', '$90,000 - $130,000', 'Lead marketing campaigns and strategy.', ARRAY['5+ years marketing experience', 'Proven track record', 'Team leadership'], ARRAY['Digital Marketing', 'SEO', 'Content Strategy', 'Analytics'], 'senior', 'business'),
('UX Designer', 'DesignHub', 'Austin, TX', 'full-time', '$80,000 - $120,000', 'Create intuitive user experiences for web and mobile apps.', ARRAY['3+ years UX design experience', 'Portfolio required', 'User research skills'], ARRAY['Figma', 'User Research', 'Prototyping', 'UI Design'], 'mid', 'creative'),
('Junior Graphic Designer', 'CreativeStudio', 'Los Angeles, CA', 'full-time', '$50,000 - $70,000', 'Design visual content for marketing materials and digital platforms.', ARRAY['Bachelor''s degree in Design', '1-2 years experience', 'Strong portfolio'], ARRAY['Adobe Creative Suite', 'Illustration', 'Typography', 'Branding'], 'entry', 'creative'),
('Financial Analyst', 'FinanceCorp', 'Chicago, IL', 'full-time', '$75,000 - $100,000', 'Analyze financial data and create investment recommendations.', ARRAY['Bachelor''s in Finance/Economics', '2+ years experience', 'Excel proficiency'], ARRAY['Financial Modeling', 'Excel', 'Data Analysis', 'SQL'], 'mid', 'finance'),
('Product Manager', 'InnovateTech', 'Seattle, WA', 'full-time', '$130,000 - $170,000', 'Drive product strategy and work with cross-functional teams.', ARRAY['5+ years product management', 'Technical background preferred', 'Strong communication'], ARRAY['Product Strategy', 'Agile', 'Data Analysis', 'Leadership'], 'senior', 'technology'),
('Content Writer Intern', 'MediaGroup', 'Remote', 'internship', '$20 - $25/hour', 'Create engaging content for blog posts and social media.', ARRAY['Currently pursuing degree', 'Strong writing skills', 'Social media knowledge'], ARRAY['Content Writing', 'SEO', 'Social Media', 'Research'], 'entry', 'creative'),
('Business Analyst', 'ConsultingFirm', 'Boston, MA', 'full-time', '$85,000 - $110,000', 'Analyze business processes and recommend improvements.', ARRAY['Bachelor''s degree', '3+ years experience', 'Strong analytical skills'], ARRAY['Business Analysis', 'SQL', 'Data Visualization', 'Process Improvement'], 'mid', 'business'),
('Sales Development Representative', 'SalesPro', 'Denver, CO', 'full-time', '$60,000 - $80,000 + commission', 'Generate leads and qualify prospects for the sales team.', ARRAY['1+ years sales experience', 'Excellent communication', 'CRM experience'], ARRAY['Sales', 'Communication', 'CRM', 'Lead Generation'], 'entry', 'business');
